import type { Live, Ad, User, DashboardStats, ViewsChartData, DeviceStats, Event, NewsArticle } from '@/types';

const MOCK_NOW = Date.UTC(2026, 5, 10, 21, 0, 0);
const mockIso = (offsetMs = 0) => new Date(MOCK_NOW + offsetMs).toISOString();

export const mockLives: Live[] = [
  {
    id: '1',
    title: 'Manchester United vs Liverpool',
    description: 'Clássico da Premier League - Rodada 20',
    thumbnail: 'https://picsum.photos/seed/football1/400/225',
    banner: 'https://picsum.photos/seed/football1/1200/600',
    sport: 'football',
    league: 'Premier League',
    teamA: 'Man. United',
    teamALogo: 'https://picsum.photos/seed/manutd/80/80',
    teamB: 'Liverpool',
    teamBLogo: 'https://picsum.photos/seed/liverpool/80/80',
    scoreA: 2,
    scoreB: 1,
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'live',
    featured: true,
    viewerCount: 125400,
    totalViews: 234567,
    scheduledAt: mockIso(),
    startedAt: mockIso(-75 * 60000),
    matchTime: "75'",
    createdAt: mockIso(-2 * 86400000),
    updatedAt: mockIso(),
    tags: ['premier-league', 'futebol', 'clássico'],
  },
  {
    id: '2',
    title: 'Real Madrid vs Barcelona',
    description: 'El Clásico - La Liga',
    thumbnail: 'https://picsum.photos/seed/football2/400/225',
    sport: 'football',
    league: 'La Liga',
    teamA: 'Real Madrid',
    teamALogo: 'https://picsum.photos/seed/realmadrid/80/80',
    teamB: 'Barcelona',
    teamBLogo: 'https://picsum.photos/seed/barcelona/80/80',
    scoreA: 1,
    scoreB: 0,
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'live',
    featured: true,
    viewerCount: 89700,
    totalViews: 180456,
    scheduledAt: mockIso(),
    startedAt: mockIso(-62 * 60000),
    matchTime: "62'",
    createdAt: mockIso(-3 * 86400000),
    updatedAt: mockIso(),
    tags: ['la-liga', 'el-clasico', 'futebol'],
  },
  {
    id: '3',
    title: 'Boston Celtics vs Miami Heat',
    description: 'NBA Regular Season',
    thumbnail: 'https://picsum.photos/seed/basketball1/400/225',
    sport: 'basketball',
    league: 'NBA',
    teamA: 'Boston Celtics',
    teamALogo: 'https://picsum.photos/seed/celtics/80/80',
    teamB: 'Miami Heat',
    teamBLogo: 'https://picsum.photos/seed/heat/80/80',
    scoreA: 78,
    scoreB: 74,
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'live',
    featured: false,
    viewerCount: 45200,
    totalViews: 98430,
    scheduledAt: mockIso(),
    startedAt: mockIso(-120 * 60000),
    matchTime: 'Q4 2:15',
    createdAt: mockIso(-1 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '4',
    title: 'Djokovic vs Alcaraz',
    description: 'ATP Wimbledon - Semifinal',
    thumbnail: 'https://picsum.photos/seed/tennis1/400/225',
    sport: 'tennis',
    league: 'ATP Wimbledon',
    teamA: 'Djokovic N.',
    teamB: 'Alcaraz C.',
    scoreA: 1,
    scoreB: 1,
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'live',
    featured: false,
    viewerCount: 61300,
    totalViews: 140234,
    scheduledAt: mockIso(),
    startedAt: mockIso(-90 * 60000),
    matchTime: 'Set 3',
    createdAt: mockIso(-1 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '5',
    title: 'PSG vs Marseille',
    description: 'Le Classique - Ligue 1',
    thumbnail: 'https://picsum.photos/seed/football3/400/225',
    sport: 'football',
    league: 'Ligue 1',
    teamA: 'PSG',
    teamALogo: '🔵',
    teamB: 'Marseille',
    teamBLogo: '⚪',
    status: 'scheduled',
    featured: false,
    viewerCount: 0,
    totalViews: 0,
    scheduledAt: mockIso(3 * 3600000),
    createdAt: mockIso(),
    updatedAt: mockIso(),
  },
  {
    id: '6',
    title: 'Flamengo vs Palmeiras',
    description: 'Campeonato Brasileiro - Rodada 35',
    thumbnail: 'https://picsum.photos/seed/football4/400/225',
    sport: 'football',
    league: 'Campeonato Brasileiro',
    teamA: 'Flamengo',
    teamALogo: '🔴',
    teamB: 'Palmeiras',
    teamBLogo: '🟢',
    status: 'scheduled',
    featured: true,
    viewerCount: 0,
    totalViews: 0,
    scheduledAt: mockIso(5 * 3600000),
    createdAt: mockIso(),
    updatedAt: mockIso(),
  },
];

export const mockAds: Ad[] = [
  {
    id: '#001',
    title: 'Banner Topo',
    campaign: 'Nike Summer 2024',
    position: 'header',
    format: 'banner',
    content: '<img src="/placeholder-ad.jpg" />',
    imageUrl: 'https://picsum.photos/seed/ad1/728/90',
    clickUrl: 'https://example.com',
    impressions: 245678,
    clicks: 3456,
    ctr: 1.41,
    revenue: 12340,
    status: 'active',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    createdAt: mockIso(-30 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '#002',
    title: 'Sidebar Right',
    campaign: 'Adidas Pro Series',
    position: 'sidebar',
    format: 'banner',
    content: '<img src="/placeholder-ad.jpg" />',
    imageUrl: 'https://picsum.photos/seed/ad2/300/250',
    clickUrl: 'https://example.com',
    impressions: 180543,
    clicks: 2123,
    ctr: 1.21,
    revenue: 8920,
    status: 'active',
    createdAt: mockIso(-25 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '#003',
    title: 'Banner Meio',
    campaign: 'ESPN Subscription',
    position: 'in_content',
    format: 'banner',
    content: '<img src="/placeholder-ad.jpg" />',
    imageUrl: 'https://picsum.photos/seed/ad3/728/90',
    clickUrl: 'https://example.com',
    impressions: 154321,
    clicks: 1876,
    ctr: 1.21,
    revenue: 7450,
    status: 'active',
    createdAt: mockIso(-20 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '#004',
    title: 'Banner Rodapé',
    campaign: 'Bet365 Sports',
    position: 'footer',
    format: 'banner',
    content: '<img src="/placeholder-ad.jpg" />',
    imageUrl: 'https://picsum.photos/seed/ad4/728/90',
    clickUrl: 'https://example.com',
    impressions: 98765,
    clicks: 987,
    ctr: 1.00,
    revenue: 4968,
    status: 'paused',
    createdAt: mockIso(-15 * 86400000),
    updatedAt: mockIso(),
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Carlos Silva',
    email: 'carlos@example.com',
    avatar: 'https://i.pravatar.cc/40?img=1',
    role: 'user',
    status: 'active',
    country: 'Brasil',
    twoFactorEnabled: false,
    emailVerified: true,
    createdAt: mockIso(-5 * 60000),
    updatedAt: mockIso(),
    lastLoginAt: mockIso(),
  },
  {
    id: '2',
    name: 'Ana Oliveira',
    email: 'ana@example.com',
    avatar: 'https://i.pravatar.cc/40?img=5',
    role: 'user',
    status: 'active',
    country: 'Portugal',
    twoFactorEnabled: true,
    emailVerified: true,
    createdAt: mockIso(-3 * 60000),
    updatedAt: mockIso(),
    lastLoginAt: mockIso(-60000),
  },
  {
    id: '3',
    name: 'João Santos',
    email: 'joao@example.com',
    avatar: 'https://i.pravatar.cc/40?img=8',
    role: 'editor',
    status: 'active',
    country: 'Brasil',
    twoFactorEnabled: false,
    emailVerified: true,
    createdAt: mockIso(-5 * 60000),
    updatedAt: mockIso(),
  },
  {
    id: '4',
    name: 'Beatriz Costa',
    email: 'beatriz@example.com',
    avatar: 'https://i.pravatar.cc/40?img=9',
    role: 'user',
    status: 'suspended',
    country: 'Brasil',
    twoFactorEnabled: false,
    emailVerified: true,
    createdAt: mockIso(-10 * 60000),
    updatedAt: mockIso(),
  },
  {
    id: '5',
    name: 'Miguel Ferreira',
    email: 'miguel@example.com',
    avatar: 'https://i.pravatar.cc/40?img=12',
    role: 'moderator',
    status: 'active',
    country: 'Angola',
    twoFactorEnabled: true,
    emailVerified: true,
    createdAt: mockIso(-15 * 60000),
    updatedAt: mockIso(),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalUsers: 12543,
  totalUsersGrowth: 12.5,
  livesTransmitted: 342,
  livesGrowth: 8.3,
  totalViews: 1234567,
  viewsGrowth: 16.7,
  adsRevenue: 45678.90,
  revenueGrowth: 18.2,
};

export const mockViewsChartData: ViewsChartData[] = [
  { date: '01/05', views: 45000, revenue: 1200 },
  { date: '05/05', views: 62000, revenue: 1800 },
  { date: '10/05', views: 58000, revenue: 1600 },
  { date: '15/05', views: 85000, revenue: 2400 },
  { date: '20/05', views: 120000, revenue: 3200 },
  { date: '25/05', views: 110000, revenue: 2900 },
  { date: '31/05', views: 155000, revenue: 4100 },
];

export const mockDeviceStats: DeviceStats = {
  mobile: 62,
  desktop: 28,
  smartTv: 10,
  tablet: 0,
};

export const mockEvents: Event[] = [
  { id: '1', title: 'Manchester United vs Liverpool', sport: 'football', league: 'Premier League', teamA: 'Man. United', teamALogo: 'https://picsum.photos/seed/manutd/80/80', teamB: 'Liverpool', teamBLogo: 'https://picsum.photos/seed/liverpool/80/80', scoreA: 2, scoreB: 1, matchTime: "75'", viewerCount: 125400, scheduledAt: mockIso(), status: 'live', createdAt: mockIso() },
  { id: '2', title: 'Real Madrid vs Barcelona', sport: 'football', league: 'La Liga', teamA: 'Real Madrid', teamALogo: 'https://picsum.photos/seed/realmadrid/80/80', teamB: 'Barcelona', teamBLogo: 'https://picsum.photos/seed/barcelona/80/80', scoreA: 1, scoreB: 0, matchTime: "62'", viewerCount: 89700, scheduledAt: mockIso(), status: 'live', createdAt: mockIso() },
  { id: '3', title: 'Boston Celtics vs Miami Heat', sport: 'basketball', league: 'NBA', teamA: 'Boston Celtics', teamALogo: 'https://picsum.photos/seed/celtics/80/80', teamB: 'Miami Heat', teamBLogo: 'https://picsum.photos/seed/heat/80/80', scoreA: 78, scoreB: 74, matchTime: 'Q4', viewerCount: 45200, scheduledAt: mockIso(), status: 'live', createdAt: mockIso() },
  { id: '4', title: 'Djokovic vs Alcaraz', sport: 'tennis', league: 'ATP Wimbledon', teamA: 'Djokovic N.', teamALogo: 'https://picsum.photos/seed/djokovic/80/80', teamB: 'Alcaraz C.', teamBLogo: 'https://picsum.photos/seed/alcaraz/80/80', scoreA: 1, scoreB: 1, matchTime: 'Set 3', viewerCount: 61300, scheduledAt: mockIso(), status: 'live', createdAt: mockIso() },
  { id: '5', title: 'PSG vs Marseille', sport: 'football', league: 'Ligue 1', teamA: 'PSG', teamB: 'Marseille', scheduledAt: mockIso(2 * 3600000), status: 'upcoming', createdAt: mockIso() },
  { id: '6', title: 'Flamengo vs Palmeiras', sport: 'football', league: 'Brasileirão', teamA: 'Flamengo', teamB: 'Palmeiras', scheduledAt: mockIso(5 * 3600000), status: 'upcoming', createdAt: mockIso() },
];

export const mockNews: NewsArticle[] = [
  {
    id: '1',
    title: 'Cristiano Ronaldo marca hat-trick histórico',
    slug: 'cristiano-ronaldo-hat-trick',
    excerpt: 'O astro português marcou três golos numa partida épica...',
    content: '<p>Cristiano Ronaldo protagonizou mais um momento histórico...</p>',
    thumbnail: 'https://picsum.photos/seed/news1/400/225',
    sport: 'football',
    tags: ['cristiano-ronaldo', 'futebol', 'hat-trick'],
    author: mockUsers[0],
    published: true,
    featured: true,
    views: 45678,
    publishedAt: mockIso(-2 * 3600000),
    createdAt: mockIso(-3 * 3600000),
    updatedAt: mockIso(),
  },
  {
    id: '2',
    title: 'LeBron James iguala recorde da NBA',
    slug: 'lebron-james-recorde-nba',
    excerpt: 'King James alcançou mais uma marca histórica na liga americana...',
    content: '<p>LeBron James continua a escrever a sua história na NBA...</p>',
    thumbnail: 'https://picsum.photos/seed/news2/400/225',
    sport: 'basketball',
    tags: ['lebron-james', 'nba', 'recorde'],
    author: mockUsers[1],
    published: true,
    featured: false,
    views: 23456,
    publishedAt: mockIso(-5 * 3600000),
    createdAt: mockIso(-6 * 3600000),
    updatedAt: mockIso(),
  },
];

export const sportCategories = [
  { id: 'football', label: 'Futebol', icon: '⚽', color: '#22C55E' },
  { id: 'basketball', label: 'Basquete', icon: '🏀', color: '#F59E0B' },
  { id: 'tennis', label: 'Tênis', icon: '🎾', color: '#84CC16' },
  { id: 'volleyball', label: 'Vôlei', icon: '🏐', color: '#3B82F6' },
  { id: 'ufc', label: 'UFC', icon: '🥊', color: '#E50914' },
  { id: 'f1', label: 'Fórmula 1', icon: '🏎️', color: '#EF4444' },
  { id: 'baseball', label: 'Beisebol', icon: '⚾', color: '#8B5CF6' },
  { id: 'other', label: 'Mais', icon: '🏅', color: '#6B7280' },
];
