export type CompetitionFormatSeed = 'groups' | 'league' | 'knockout';

export interface CompetitionSeed {
  id: string;
  name: string;
  slug: string;
  season: string;
  format: CompetitionFormatSeed;
  country: string;
  description: string;
  heroBadge?: string;
  heroBadgeIcon?: string;
  heroTitleLine1?: string;
  heroTitleLine2?: string;
  sectionTitle?: string;
  themeColor?: string;
  thumbnail?: string;
  banner?: string;
}

export const COMPETITION_MEDIA: Record<string, { themeColor: string; thumbnail?: string; banner?: string }> = {
  'copa-do-mundo': {
    themeColor: '#FFD700',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/2026_FIFA_World_Cup.svg/120px-2026_FIFA_World_Cup.svg.png',
    banner: 'https://images.unsplash.com/photo-1574629810360-7efbbe195778?auto=format&fit=crop&w=1600&q=80',
  },
  'premier-league': {
    themeColor: '#3D195B',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/f/f2/Premier_League_Logo.svg',
    banner: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1600&q=80',
  },
  'fa-cup': { themeColor: '#BB0000' },
  'efl-cup': { themeColor: '#00A650' },
  'la-liga': {
    themeColor: '#EE8707',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/LaLiga_Santander_2023_Vertical_Logo.svg/120px-LaLiga_Santander_2023_Vertical_Logo.svg.png',
    banner: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1600&q=80',
  },
  'copa-del-rey': { themeColor: '#C60C30' },
  'supercopa-espana': { themeColor: '#C60C30' },
  bundesliga: {
    themeColor: '#D20515',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/d/df/Bundesliga_logo_%282017%29.svg',
    banner: 'https://images.unsplash.com/photo-1574629810360-7efbbe195778?auto=format&fit=crop&w=1600&q=80',
  },
  'dfb-pokal': { themeColor: '#FFCC00' },
  'serie-a': {
    themeColor: '#008FD7',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Serie_A_logo_2022.svg/120px-Serie_A_logo_2022.svg.png',
  },
  'coppa-italia': { themeColor: '#008FD7' },
  'ligue-1': {
    themeColor: '#DAE025',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Ligue_1_Uber_Eats_logo.svg/120px-Ligue_1_Uber_Eats_logo.svg.png',
  },
  'coupe-de-france': { themeColor: '#002654' },
  'liga-portugal': {
    themeColor: '#00A859',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Liga_Portugal_logo.svg/120px-Liga_Portugal_logo.svg.png',
  },
  'taca-portugal': { themeColor: '#00A859' },
  'taca-liga': { themeColor: '#00A859' },
  brasileirao: { themeColor: '#009C3B' },
  'copa-brasil': { themeColor: '#009C3B' },
  'supercopa-brasil': { themeColor: '#009C3B' },
  'champions-league': {
    themeColor: '#0A1D56',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/UEFA_Champions_League_logo_2.svg/120px-UEFA_Champions_League_logo_2.svg.png',
    banner: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=1600&q=80',
  },
  'europa-league': { themeColor: '#FF6900' },
  'conference-league': { themeColor: '#00BF8F' },
  'uefa-super-cup': { themeColor: '#0A1D56' },
  euro: { themeColor: '#003399' },
  'nations-league': { themeColor: '#003399' },
  eredivisie: { themeColor: '#FF6600' },
  'liga-belgica': { themeColor: '#1A1A6E' },
  'super-lig': { themeColor: '#E30613' },
  'scottish-premiership': { themeColor: '#003DA5' },
};

export function getCompetitionSeedMedia(slug: string) {
  return COMPETITION_MEDIA[slug];
}

export const COMPETITION_SEEDS: CompetitionSeed[] = [
  // ——— Inglaterra ———
  {
    id: 'comp-premier-league',
    name: 'Premier League',
    slug: 'premier-league',
    season: '2025-26',
    format: 'league',
    country: 'Inglaterra',
    description: 'A principal liga de futebol da Inglaterra.',
    heroBadge: 'Premier League',
    heroBadgeIcon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    heroTitleLine1: 'PREMIER',
    heroTitleLine2: 'LEAGUE',
    sectionTitle: 'Premier League',
  },
  {
    id: 'comp-fa-cup',
    name: 'FA Cup',
    slug: 'fa-cup',
    season: '2025-26',
    format: 'knockout',
    country: 'Inglaterra',
    description: 'A taça de futebol mais antiga do mundo.',
    heroBadge: 'FA Cup',
    heroTitleLine1: 'FA',
    heroTitleLine2: 'CUP',
    sectionTitle: 'FA Cup',
  },
  {
    id: 'comp-efl-cup',
    name: 'EFL Cup',
    slug: 'efl-cup',
    season: '2025-26',
    format: 'knockout',
    country: 'Inglaterra',
    description: 'Taça da Liga Inglesa (Carabao Cup).',
    heroBadge: 'EFL Cup',
    heroTitleLine1: 'EFL',
    heroTitleLine2: 'CUP',
    sectionTitle: 'EFL Cup',
  },
  // ——— Espanha ———
  {
    id: 'comp-la-liga',
    name: 'La Liga',
    slug: 'la-liga',
    season: '2025-26',
    format: 'league',
    country: 'Espanha',
    description: 'Campeonato Espanhol de Futebol.',
    heroBadge: 'La Liga',
    heroBadgeIcon: '🇪🇸',
    heroTitleLine1: 'LA',
    heroTitleLine2: 'LIGA',
    sectionTitle: 'La Liga',
  },
  {
    id: 'comp-copa-del-rey',
    name: 'Copa del Rey',
    slug: 'copa-del-rey',
    season: '2025-26',
    format: 'knockout',
    country: 'Espanha',
    description: 'Taça de Espanha.',
    heroBadge: 'Copa del Rey',
    heroTitleLine1: 'COPA',
    heroTitleLine2: 'DEL REY',
    sectionTitle: 'Copa del Rey',
  },
  {
    id: 'comp-supercopa-espana',
    name: 'Supercopa de España',
    slug: 'supercopa-espana',
    season: '2025-26',
    format: 'knockout',
    country: 'Espanha',
    description: 'Supercopa da Espanha.',
    heroBadge: 'Supercopa',
    sectionTitle: 'Supercopa de España',
  },
  // ——— Alemanha ———
  {
    id: 'comp-bundesliga',
    name: 'Bundesliga',
    slug: 'bundesliga',
    season: '2025-26',
    format: 'league',
    country: 'Alemanha',
    description: 'Campeonato Alemão de Futebol.',
    heroBadge: 'Bundesliga',
    heroBadgeIcon: '🇩🇪',
    heroTitleLine1: 'BUNDES',
    heroTitleLine2: 'LIGA',
    sectionTitle: 'Bundesliga',
  },
  {
    id: 'comp-dfb-pokal',
    name: 'DFB-Pokal',
    slug: 'dfb-pokal',
    season: '2025-26',
    format: 'knockout',
    country: 'Alemanha',
    description: 'Taça da Alemanha.',
    heroBadge: 'DFB-Pokal',
    heroTitleLine1: 'DFB',
    heroTitleLine2: 'POKAL',
    sectionTitle: 'DFB-Pokal',
  },
  // ——— Itália ———
  {
    id: 'comp-serie-a',
    name: 'Serie A',
    slug: 'serie-a',
    season: '2025-26',
    format: 'league',
    country: 'Itália',
    description: 'Campeonato Italiano de Futebol.',
    heroBadge: 'Serie A',
    heroBadgeIcon: '🇮🇹',
    heroTitleLine1: 'SERIE',
    heroTitleLine2: 'A',
    sectionTitle: 'Serie A',
  },
  {
    id: 'comp-coppa-italia',
    name: 'Coppa Italia',
    slug: 'coppa-italia',
    season: '2025-26',
    format: 'knockout',
    country: 'Itália',
    description: 'Taça de Itália.',
    heroBadge: 'Coppa Italia',
    sectionTitle: 'Coppa Italia',
  },
  // ——— França ———
  {
    id: 'comp-ligue-1',
    name: 'Ligue 1',
    slug: 'ligue-1',
    season: '2025-26',
    format: 'league',
    country: 'França',
    description: 'Campeonato Francês de Futebol.',
    heroBadge: 'Ligue 1',
    heroBadgeIcon: '🇫🇷',
    heroTitleLine1: 'LIGUE',
    heroTitleLine2: '1',
    sectionTitle: 'Ligue 1',
  },
  {
    id: 'comp-coupe-de-france',
    name: 'Coupe de France',
    slug: 'coupe-de-france',
    season: '2025-26',
    format: 'knockout',
    country: 'França',
    description: 'Taça de França.',
    heroBadge: 'Coupe de France',
    sectionTitle: 'Coupe de France',
  },
  // ——— Portugal ———
  {
    id: 'comp-liga-portugal',
    name: 'Liga Portugal',
    slug: 'liga-portugal',
    season: '2025-26',
    format: 'league',
    country: 'Portugal',
    description: 'Campeonato Português de Futebol.',
    heroBadge: 'Liga Portugal',
    heroBadgeIcon: '🇵🇹',
    heroTitleLine1: 'LIGA',
    heroTitleLine2: 'PORTUGAL',
    sectionTitle: 'Liga Portugal',
  },
  {
    id: 'comp-taca-portugal',
    name: 'Taça de Portugal',
    slug: 'taca-portugal',
    season: '2025-26',
    format: 'knockout',
    country: 'Portugal',
    description: 'Taça de Portugal em futebol.',
    heroBadge: 'Taça de Portugal',
    sectionTitle: 'Taça de Portugal',
  },
  {
    id: 'comp-taca-liga',
    name: 'Taça da Liga',
    slug: 'taca-liga',
    season: '2025-26',
    format: 'knockout',
    country: 'Portugal',
    description: 'Taça da Liga Portuguesa.',
    heroBadge: 'Taça da Liga',
    sectionTitle: 'Taça da Liga',
  },
  // ——— Brasil ———
  {
    id: 'comp-brasileirao',
    name: 'Brasileirão',
    slug: 'brasileirao',
    season: '2026',
    format: 'league',
    country: 'Brasil',
    description: 'Campeonato Brasileiro de Futebol — Série A.',
    heroBadge: 'Brasileirão',
    heroBadgeIcon: '🇧🇷',
    heroTitleLine1: 'BRASILEIRÃO',
    heroTitleLine2: 'SÉRIE A',
    sectionTitle: 'Brasileirão',
  },
  {
    id: 'comp-copa-brasil',
    name: 'Copa do Brasil',
    slug: 'copa-brasil',
    season: '2026',
    format: 'knockout',
    country: 'Brasil',
    description: 'Taça nacional do Brasil.',
    heroBadge: 'Copa do Brasil',
    sectionTitle: 'Copa do Brasil',
  },
  {
    id: 'comp-supercopa-brasil',
    name: 'Supercopa do Brasil',
    slug: 'supercopa-brasil',
    season: '2026',
    format: 'knockout',
    country: 'Brasil',
    description: 'Supercopa do Brasil.',
    heroBadge: 'Supercopa do Brasil',
    sectionTitle: 'Supercopa do Brasil',
  },
  // ——— UEFA ———
  {
    id: 'comp-ucl',
    name: 'UEFA Champions League',
    slug: 'champions-league',
    season: '2025-26',
    format: 'groups',
    country: 'UEFA',
    description: 'A principal competição de clubes da Europa.',
    heroBadge: 'UEFA Champions League',
    heroBadgeIcon: '🏆',
    heroTitleLine1: 'CHAMPIONS',
    heroTitleLine2: 'LEAGUE',
    sectionTitle: 'UEFA Champions League',
  },
  {
    id: 'comp-uel',
    name: 'UEFA Europa League',
    slug: 'europa-league',
    season: '2025-26',
    format: 'groups',
    country: 'UEFA',
    description: 'Segunda competição europeia de clubes.',
    heroBadge: 'UEFA Europa League',
    heroTitleLine1: 'EUROPA',
    heroTitleLine2: 'LEAGUE',
    sectionTitle: 'UEFA Europa League',
  },
  {
    id: 'comp-uecl',
    name: 'UEFA Conference League',
    slug: 'conference-league',
    season: '2025-26',
    format: 'groups',
    country: 'UEFA',
    description: 'Terceira competição europeia de clubes.',
    heroBadge: 'UEFA Conference League',
    sectionTitle: 'UEFA Conference League',
  },
  {
    id: 'comp-uefa-super-cup',
    name: 'UEFA Super Cup',
    slug: 'uefa-super-cup',
    season: '2025-26',
    format: 'knockout',
    country: 'UEFA',
    description: 'Supercopa Europeia.',
    heroBadge: 'UEFA Super Cup',
    sectionTitle: 'UEFA Super Cup',
  },
  {
    id: 'comp-euro',
    name: 'UEFA Euro',
    slug: 'euro',
    season: '2028',
    format: 'groups',
    country: 'UEFA',
    description: 'Campeonato Europeu de Seleções.',
    heroBadge: 'UEFA Euro',
    heroTitleLine1: 'EURO',
    heroTitleLine2: '2028',
    sectionTitle: 'UEFA Euro',
  },
  {
    id: 'comp-uefa-nations-league',
    name: 'UEFA Nations League',
    slug: 'nations-league',
    season: '2024-25',
    format: 'groups',
    country: 'UEFA',
    description: 'Liga das Nações da UEFA.',
    heroBadge: 'UEFA Nations League',
    sectionTitle: 'UEFA Nations League',
  },
  // ——— Outras ligas europeias ———
  {
    id: 'comp-eredivisie',
    name: 'Eredivisie',
    slug: 'eredivisie',
    season: '2025-26',
    format: 'league',
    country: 'Países Baixos',
    description: 'Campeonato Holandês de Futebol.',
    heroBadge: 'Eredivisie',
    heroBadgeIcon: '🇳🇱',
    sectionTitle: 'Eredivisie',
  },
  {
    id: 'comp-liga-belgica',
    name: 'Pro League',
    slug: 'liga-belgica',
    season: '2025-26',
    format: 'league',
    country: 'Bélgica',
    description: 'Campeonato Belga de Futebol.',
    heroBadge: 'Pro League',
    heroBadgeIcon: '🇧🇪',
    sectionTitle: 'Pro League',
  },
  {
    id: 'comp-super-lig',
    name: 'Süper Lig',
    slug: 'super-lig',
    season: '2025-26',
    format: 'league',
    country: 'Turquia',
    description: 'Campeonato Turco de Futebol.',
    heroBadge: 'Süper Lig',
    heroBadgeIcon: '🇹🇷',
    sectionTitle: 'Süper Lig',
  },
  {
    id: 'comp-liga-scotland',
    name: 'Scottish Premiership',
    slug: 'scottish-premiership',
    season: '2025-26',
    format: 'league',
    country: 'Escócia',
    description: 'Campeonato Escocês de Futebol.',
    heroBadge: 'Scottish Premiership',
    heroBadgeIcon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    sectionTitle: 'Scottish Premiership',
  },
];
