import type { Live, Ad, User, DashboardStats, ViewsChartData, DeviceStats, Event, NewsArticle } from '@/types';

const MOCK_NOW = Date.UTC(2026, 5, 16, 20, 0, 0);
const mockIso = (offsetMs = 0) => new Date(MOCK_NOW + offsetMs).toISOString();

// ─── Real logo URLs via api-football CDN & Wikipedia Commons ───
const LOGOS = {
  manutd:      "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg",
  liverpool:   "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
  realmadrid:  "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
  barcelona:   "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
  psg:         "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg",
  marseille:   "https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg",
  flamengo:    "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flamengo_braz_logo.svg",
  palmeiras:   "https://upload.wikimedia.org/wikipedia/commons/1/10/Palmeiras_logo.svg",
  celtics:     "https://upload.wikimedia.org/wikipedia/en/3/3a/Boston_Celtics_Banner.svg",
  heat:        "https://upload.wikimedia.org/wikipedia/en/f/fb/Miami_Heat_logo.svg",
  // Leagues
  premierleague: "https://upload.wikimedia.org/wikipedia/en/f/f2/Premier_League_Logo.svg",
  laliga:      "https://upload.wikimedia.org/wikipedia/commons/1/13/LaLiga.svg",
  ligue1:      "https://upload.wikimedia.org/wikipedia/en/b/ba/Ligue_1_Uber_Eats_logo.svg",
  brasileirao: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Campeonato_Brasileiro_-_S%C3%A9rie_A_logo.svg",
  nba:         "https://upload.wikimedia.org/wikipedia/en/0/03/National_Basketball_Association_logo.svg",
  atp:         "https://upload.wikimedia.org/wikipedia/en/3/3f/ATP_Tour_logo.svg",
};

export const mockLives: Live[] = [
  {
    id: '1',
    title: 'Manchester United vs Liverpool',
    description: 'Clássico da Premier League - Rodada 20',
    thumbnail: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
    banner: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1600&q=80',
    sport: 'football',
    league: 'Premier League',
    leagueLogo: LOGOS.premierleague,
    teamA: 'Man. United',
    teamALogo: LOGOS.manutd,
    teamB: 'Liverpool',
    teamBLogo: LOGOS.liverpool,
    scoreA: 2,
    scoreB: 1,
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'live',
    featured: true,
    viewerCount: 125400,
    totalViews: 234567,
    scheduledAt: mockIso(),
    startedAt: mockIso(-75 * 60000),
    matchTime: "75'",
    createdAt: mockIso(-2 * 86400000),
    updatedAt: mockIso(),
    tags: ['premier-league', 'futebol', 'classico'],
  },
  {
    id: '2',
    title: 'Real Madrid vs Barcelona',
    description: 'El Clásico - La Liga',
    thumbnail: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&q=80',
    banner: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=1600&q=80',
    sport: 'football',
    league: 'La Liga',
    leagueLogo: LOGOS.laliga,
    teamA: 'Real Madrid',
    teamALogo: LOGOS.realmadrid,
    teamB: 'Barcelona',
    teamBLogo: LOGOS.barcelona,
    scoreA: 1,
    scoreB: 0,
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'live',
    featured: true,
    viewerCount: 89700,
    totalViews: 180456,
    scheduledAt: mockIso(),
    startedAt: mockIso(-62 * 60000),
    matchTime: "62'",
    createdAt: mockIso(-3 * 86400000),
    updatedAt: mockIso(),
    tags: ['la-liga', 'el-clasico', 'futebol'],
  },
  {
    id: '3',
    title: 'Boston Celtics vs Miami Heat',
    description: 'NBA Regular Season',
    thumbnail: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80',
    sport: 'basketball',
    league: 'NBA',
    leagueLogo: LOGOS.nba,
    teamA: 'Boston Celtics',
    teamALogo: LOGOS.celtics,
    teamB: 'Miami Heat',
    teamBLogo: LOGOS.heat,
    scoreA: 78,
    scoreB: 74,
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'live',
    featured: false,
    viewerCount: 45200,
    totalViews: 98430,
    scheduledAt: mockIso(),
    startedAt: mockIso(-120 * 60000),
    matchTime: 'Q4 2:15',
    createdAt: mockIso(-1 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '4',
    title: 'Djokovic vs Alcaraz',
    description: 'ATP Wimbledon - Semifinal',
    thumbnail: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&q=80',
    sport: 'tennis',
    league: 'ATP Wimbledon',
    teamA: 'Djokovic N.',
    teamB: 'Alcaraz C.',
    scoreA: 1,
    scoreB: 1,
    hlsUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'live',
    featured: false,
    viewerCount: 61300,
    totalViews: 140234,
    scheduledAt: mockIso(),
    startedAt: mockIso(-90 * 60000),
    matchTime: 'Set 3',
    createdAt: mockIso(-1 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '5',
    title: 'PSG vs Marseille',
    description: 'Le Classique - Ligue 1',
    thumbnail: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&q=80',
    sport: 'football',
    league: 'Ligue 1',
    leagueLogo: LOGOS.ligue1,
    teamA: 'PSG',
    teamALogo: LOGOS.psg,
    teamB: 'Marseille',
    teamBLogo: LOGOS.marseille,
    status: 'scheduled',
    featured: false,
    viewerCount: 0,
    totalViews: 0,
    scheduledAt: mockIso(3 * 3600000),
    createdAt: mockIso(),
    updatedAt: mockIso(),
  },
  {
    id: '6',
    title: 'Flamengo vs Palmeiras',
    description: 'Campeonato Brasileiro - Rodada 35',
    thumbnail: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
    sport: 'football',
    league: 'Brasileirao',
    leagueLogo: LOGOS.brasileirao,
    teamA: 'Flamengo',
    teamALogo: LOGOS.flamengo,
    teamB: 'Palmeiras',
    teamBLogo: LOGOS.palmeiras,
    status: 'scheduled',
    featured: true,
    viewerCount: 0,
    totalViews: 0,
    scheduledAt: mockIso(5 * 3600000),
    createdAt: mockIso(),
    updatedAt: mockIso(),
  },
];

export const mockAds: Ad[] = [
  {
    id: '#001',
    title: 'Banner Topo',
    campaign: 'Nike Summer 2026',
    position: 'header',
    format: 'banner',
    content: '',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=80',
    clickUrl: 'https://example.com',
    impressions: 245678,
    clicks: 3456,
    ctr: 1.41,
    revenue: 12340,
    status: 'active',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    createdAt: mockIso(-30 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '#002',
    title: 'Sidebar Right',
    campaign: 'Adidas Pro Series',
    position: 'sidebar',
    format: 'banner',
    content: '',
    imageUrl: 'https://images.unsplash.com/photo-1556906781-9a412961a28c?w=600&q=80',
    clickUrl: 'https://example.com',
    impressions: 180543,
    clicks: 2123,
    ctr: 1.21,
    revenue: 8920,
    status: 'active',
    createdAt: mockIso(-25 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '#003',
    title: 'Banner Meio',
    campaign: 'ESPN+ Subscription',
    position: 'in_content',
    format: 'banner',
    content: '',
    imageUrl: 'https://images.unsplash.com/photo-1601850494422-3cf14624b0b3?w=1200&q=80',
    clickUrl: 'https://example.com',
    impressions: 154321,
    clicks: 1876,
    ctr: 1.21,
    revenue: 7450,
    status: 'active',
    createdAt: mockIso(-20 * 86400000),
    updatedAt: mockIso(),
  },
  {
    id: '#004',
    title: 'Banner Rodape',
    campaign: 'SportsBet',
    position: 'footer',
    format: 'banner',
    content: '',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80',
    clickUrl: 'https://example.com',
    impressions: 98765,
    clicks: 987,
    ctr: 1.00,
    revenue: 4968,
    status: 'active',
    createdAt: mockIso(-15 * 86400000),
    updatedAt: mockIso(),
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Carlos Silva',
    email: 'carlos@example.com',
    avatar: 'https://i.pravatar.cc/40?img=1',
    role: 'user',
    status: 'active',
    country: 'Brasil',
    twoFactorEnabled: false,
    emailVerified: true,
    createdAt: mockIso(-5 * 60000),
    updatedAt: mockIso(),
    lastLoginAt: mockIso(),
  },
  {
    id: '2',
    name: 'Ana Oliveira',
    email: 'ana@example.com',
    avatar: 'https://i.pravatar.cc/40?img=5',
    role: 'user',
    status: 'active',
    country: 'Portugal',
    twoFactorEnabled: true,
    emailVerified: true,
    createdAt: mockIso(-3 * 60000),
    updatedAt: mockIso(),
    lastLoginAt: mockIso(-60000),
  },
  {
    id: '3',
    name: 'Joao Santos',
    email: 'joao@example.com',
    avatar: 'https://i.pravatar.cc/40?img=8',
    role: 'editor',
    status: 'active',
    country: 'Brasil',
    twoFactorEnabled: false,
    emailVerified: true,
    createdAt: mockIso(-5 * 60000),
    updatedAt: mockIso(),
  },
  {
    id: '4',
    name: 'Beatriz Costa',
    email: 'beatriz@example.com',
    avatar: 'https://i.pravatar.cc/40?img=9',
    role: 'user',
    status: 'suspended',
    country: 'Brasil',
    twoFactorEnabled: false,
    emailVerified: true,
    createdAt: mockIso(-10 * 60000),
    updatedAt: mockIso(),
  },
  {
    id: '5',
    name: 'Miguel Ferreira',
    email: 'miguel@example.com',
    avatar: 'https://i.pravatar.cc/40?img=12',
    role: 'moderator',
    status: 'active',
    country: 'Angola',
    twoFactorEnabled: true,
    emailVerified: true,
    createdAt: mockIso(-15 * 60000),
    updatedAt: mockIso(),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalUsers: 12543,
  totalUsersGrowth: 12.5,
  livesTransmitted: 342,
  livesGrowth: 8.3,
  totalViews: 1234567,
  viewsGrowth: 16.7,
  adsRevenue: 45678.90,
  revenueGrowth: 18.2,
};

export const mockViewsChartData: ViewsChartData[] = [
  { date: '01/05', views: 45000, revenue: 1200 },
  { date: '05/05', views: 62000, revenue: 1800 },
  { date: '10/05', views: 58000, revenue: 1600 },
  { date: '15/05', views: 85000, revenue: 2400 },
  { date: '20/05', views: 120000, revenue: 3200 },
  { date: '25/05', views: 110000, revenue: 2900 },
  { date: '31/05', views: 155000, revenue: 4100 },
];

export const mockDeviceStats: DeviceStats = {
  mobile: 62,
  desktop: 28,
  smartTv: 10,
  tablet: 0,
};

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Manchester United vs Liverpool',
    sport: 'football',
    league: 'Premier League',
    leagueLogo: LOGOS.premierleague,
    teamA: 'Man. United',
    teamALogo: LOGOS.manutd,
    teamB: 'Liverpool',
    teamBLogo: LOGOS.liverpool,
    scoreA: 2,
    scoreB: 1,
    matchTime: "75'",
    viewerCount: 125400,
    scheduledAt: mockIso(),
    status: 'live',
    createdAt: mockIso(),
  },
  {
    id: '2',
    title: 'Real Madrid vs Barcelona',
    sport: 'football',
    league: 'La Liga',
    leagueLogo: LOGOS.laliga,
    teamA: 'Real Madrid',
    teamALogo: LOGOS.realmadrid,
    teamB: 'Barcelona',
    teamBLogo: LOGOS.barcelona,
    scoreA: 1,
    scoreB: 0,
    matchTime: "62'",
    viewerCount: 89700,
    scheduledAt: mockIso(),
    status: 'live',
    createdAt: mockIso(),
  },
  {
    id: '3',
    title: 'Boston Celtics vs Miami Heat',
    sport: 'basketball',
    league: 'NBA',
    leagueLogo: LOGOS.nba,
    teamA: 'Boston Celtics',
    teamALogo: LOGOS.celtics,
    teamB: 'Miami Heat',
    teamBLogo: LOGOS.heat,
    scoreA: 78,
    scoreB: 74,
    matchTime: 'Q4',
    viewerCount: 45200,
    scheduledAt: mockIso(),
    status: 'live',
    createdAt: mockIso(),
  },
  {
    id: '4',
    title: 'Djokovic vs Alcaraz',
    sport: 'tennis',
    league: 'ATP Wimbledon',
    teamA: 'Djokovic N.',
    teamB: 'Alcaraz C.',
    scoreA: 1,
    scoreB: 1,
    matchTime: 'Set 3',
    viewerCount: 61300,
    scheduledAt: mockIso(),
    status: 'live',
    createdAt: mockIso(),
  },
  {
    id: '5',
    title: 'PSG vs Marseille',
    sport: 'football',
    league: 'Ligue 1',
    leagueLogo: LOGOS.ligue1,
    teamA: 'PSG',
    teamALogo: LOGOS.psg,
    teamB: 'Marseille',
    teamBLogo: LOGOS.marseille,
    scheduledAt: mockIso(2 * 3600000),
    status: 'upcoming',
    createdAt: mockIso(),
  },
  {
    id: '6',
    title: 'Flamengo vs Palmeiras',
    sport: 'football',
    league: 'Brasileirao',
    leagueLogo: LOGOS.brasileirao,
    teamA: 'Flamengo',
    teamALogo: LOGOS.flamengo,
    teamB: 'Palmeiras',
    teamBLogo: LOGOS.palmeiras,
    scheduledAt: mockIso(5 * 3600000),
    status: 'upcoming',
    createdAt: mockIso(),
  },
  {
    id: '7',
    title: 'Portugal vs Espanha',
    sport: 'football',
    league: 'Copa do Mundo 2026',
    teamA: 'Portugal',
    teamALogo: '🇵🇹',
    teamB: 'Espanha',
    teamBLogo: '🇪🇸',
    scoreA: 2,
    scoreB: 1,
    scheduledAt: mockIso(-1 * 86400000),
    status: 'finished',
    createdAt: mockIso(),
  },
  {
    id: '8',
    title: 'Brasil vs Argentina',
    sport: 'football',
    league: 'Copa do Mundo 2026',
    teamA: 'Brasil',
    teamALogo: '🇧🇷',
    teamB: 'Argentina',
    teamBLogo: '🇦🇷',
    scheduledAt: mockIso(2 * 86400000),
    status: 'upcoming',
    createdAt: mockIso(),
  },
];

export const mockNews: NewsArticle[] = [
  {
    id: '1',
    title: 'Cristiano Ronaldo marca hat-trick historico',
    slug: 'cristiano-ronaldo-hat-trick',
    excerpt: 'O astro portugues marcou tres golos numa partida epica...',
    content: '<p>Cristiano Ronaldo protagonizou mais um momento historico...</p>',
    thumbnail: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&q=80',
    sport: 'football',
    tags: ['cristiano-ronaldo', 'futebol', 'hat-trick'],
    author: mockUsers[0],
    published: true,
    featured: true,
    views: 45678,
    publishedAt: mockIso(-2 * 3600000),
    createdAt: mockIso(-3 * 3600000),
    updatedAt: mockIso(),
  },
  {
    id: '2',
    title: 'LeBron James iguala recorde da NBA',
    slug: 'lebron-james-recorde-nba',
    excerpt: 'King James alcancou mais uma marca historica na liga americana...',
    content: '<p>LeBron James continua a escrever a sua historia na NBA...</p>',
    thumbnail: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80',
    sport: 'basketball',
    tags: ['lebron-james', 'nba', 'recorde'],
    author: mockUsers[1],
    published: true,
    featured: false,
    views: 23456,
    publishedAt: mockIso(-5 * 3600000),
    createdAt: mockIso(-6 * 3600000),
    updatedAt: mockIso(),
  },
];

export const sportCategories = [
  { id: 'football',   label: 'Futebol',   icon: '⚽', color: '#22C55E' },
  { id: 'basketball', label: 'Basquete',  icon: '🏀', color: '#F59E0B' },
  { id: 'tennis',     label: 'Tênis',     icon: '🎾', color: '#84CC16' },
  { id: 'volleyball', label: 'Vôlei',     icon: '🏐', color: '#3B82F6' },
  { id: 'ufc',        label: 'UFC / MMA', icon: '🥊', color: '#E50914' },
  { id: 'f1',         label: 'Fórmula 1', icon: '🏎️', color: '#EF4444' },
  { id: 'baseball',   label: 'Beisebol',  icon: '⚾', color: '#8B5CF6' },
  { id: 'other',      label: 'Mais',      icon: '🏅', color: '#6B7280' },
];

// ─── Real league logos (CDN-served SVGs / PNGs) ───────────────────────────────
export const LEAGUE_LOGOS: Record<string, { name: string; logo: string; country: string; color: string }> = {
  premierleague: {
    name: 'Premier League',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/f2/Premier_League_Logo.svg',
    country: 'Inglaterra',
    color: '#3D195B',
  },
  laliga: {
    name: 'La Liga',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/13/LaLiga.svg',
    country: 'Espanha',
    color: '#FF4B00',
  },
  bundesliga: {
    name: 'Bundesliga',
    logo: 'https://upload.wikimedia.org/wikipedia/en/d/df/Bundesliga_logo_%282017%29.svg',
    country: 'Alemanha',
    color: '#D3010C',
  },
  seriea: {
    name: 'Serie A',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Serie_A_logo_%282019%29.svg',
    country: 'Itália',
    color: '#1A56DB',
  },
  ligue1: {
    name: 'Ligue 1',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Ligue_1_Uber_Eats_logo.svg',
    country: 'França',
    color: '#FFFFFF',
  },
  championsleague: {
    name: 'Champions League',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/bf/UEFA_Champions_League_logo_2.svg',
    country: 'Europa',
    color: '#0B1F6B',
  },
  brasileirao: {
    name: 'Brasileirão Série A',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Campeonato_Brasileiro_-_S%C3%A9rie_A_logo.svg',
    country: 'Brasil',
    color: '#009C3B',
  },
  nba: {
    name: 'NBA',
    logo: 'https://upload.wikimedia.org/wikipedia/en/0/03/National_Basketball_Association_logo.svg',
    country: 'EUA',
    color: '#1D428A',
  },
  atp: {
    name: 'ATP Tour',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/3f/ATP_Tour_logo.svg',
    country: 'Mundial',
    color: '#012169',
  },
  ufc: {
    name: 'UFC',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/92/UFC_Logo.svg',
    country: 'EUA',
    color: '#D20A0A',
  },
  f1: {
    name: 'Fórmula 1',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/33/F1_logo_2.svg',
    country: 'Mundial',
    color: '#E10600',
  },
  copaamerica: {
    name: 'Copa América',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Copa_America_logo.svg/200px-Copa_America_logo.svg.png',
    country: 'América do Sul',
    color: '#003087',
  },
  wnba: {
    name: 'WNBA',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/f8/WNBA_Official_Logo.svg',
    country: 'EUA',
    color: '#FF6900',
  },
  mlb: {
    name: 'MLB',
    logo: 'https://upload.wikimedia.org/wikipedia/en/a/a6/Major_League_Baseball_logo.svg',
    country: 'EUA',
    color: '#002D72',
  },
};
